### ISSUE TITLE
Multiple links in a single comment

### ISSUE THREAD

**Issue by dumbasPL** [laurinneff/no-google-amp-bot#10]
When someone posts a comment containing two or more google amp links only the first one gets processed.

Would be nice if the bot could process multiple links and display them in the same order as they appear in the comment.

**Comment by lunananananananana** [comment]
The bot should be able to handle multiple links ([example](https://www.reddit.com/r/Bitcoin/comments/lola70/-/go8oen0)). Can you link the comment where it only found one link?

**Comment by dumbasPL** [comment]
Now I'm mad at myself for not saving the link. I don't even remember the sub i was on. I think i was on mobile so i don't even have browser history.

I'll try to find it but it will be hard.
