### ISSUE TITLE
Verbosity

### ISSUE THREAD

**Issue by nicgarner** [laurinneff/no-google-amp-bot#2]
Please, please, please: if your bot has to exist, can't it be less verbose? I think it would really improve the reading experience on Reddit if its comments were as brief as possible. I'd advocate for something like:

> Non-AMP link: https://www.example.com
> [Why?](https://laurinneff.ch/2020/10/17/nogoogleampbot/) 

That is a service. Its current verbosity is self-important, self-promoting spam.

**Comment by lunananananananana** [comment]
True that the current template is very long. I'll do this tomorrow evening if I have time.

**Comment by lunananananananana** [comment]
I've now shortened the template to be just two lines long. I'll close this issue once the new version is up on my server.
